# Generated by Django 5.1.2 on 2024-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='series_vistas',
            field=models.ManyToManyField(to='filme.serie'),
        ),
    ]
