# Generated by Django 5.1.2 on 2024-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_filme_link_usuario_series_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='tipo',
            field=models.CharField(default='filme', max_length=10),
        ),
        migrations.AddField(
            model_name='serie',
            name='tipo',
            field=models.CharField(default='serie', max_length=10),
        ),
    ]
