# Generated by Django 5.1.2 on 2024-11-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_filme_tipo_serie_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='filme',
            new_name='serie',
        ),
    ]
