# Generated by Django 5.1.2 on 2024-11-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_rename_filme_episodio_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='tipo',
        ),
    ]
